### ISSUE TITLE
Implementing SDE nodes

### ISSUE THREAD

**Issue by antonplietzsch** [FHell/NetworkDynamics.jl#12]
We need to implement a node type for stochastic differential equations.

**Comment by lindnemi** [comment]
It seems we can get pretty far into stochastic modeling without implementing a specific node type. I attached an image showing a network diffusion with additive, pulsating noise at the edges. The generating script can be found in the [examples section](https://github.com/FHell/NetworkDynamics.jl/blob/master/examples/sde.jl).
![sde](https://user-images.githubusercontent.com/56298440/78353138-ddd70300-75a9-11ea-930a-0a004e7f1099.png)

**Comment by lindnemi** [comment]
Issue for tracking documentation of the feature: https://github.com/FHell/NetworkDynamics.jl/issues/26
