### ISSUE TITLE
Narrow dependencies to DifferentialEquations.jl

### ISSUE THREAD

**Issue by janlisse** [FHell/NetworkDynamics.jl#13]
For PowerDynamics we currently only need OrdinaryDiffEq, but NetworkDynamics includes the full DifferentialEquestions.jl dependency which includes various side packages (stochastical, financial etc..)
we don't need. Changes made in those side projects sometimes even break our build like here: https://travis-ci.org/JuliaEnergy/PowerDynamics.jl/builds/613460044
It would be nice if NetworkDynamics could narrow its dependencies to OrdinaryDiffEq and maybe other mandatory packages but not the full DifferentialEquations ecosystem.
See also: http://docs.juliadiffeq.org/stable/features/low_dep.html

**Comment by FHell** [comment]
Implemented in the Major Rewrite.

**Comment by lindnemi** [comment]
I'm closing the issue, since it seems to be solved.
