### ISSUE TITLE
error in diffusion_test.jl

### ISSUE THREAD

**Issue by lindnemi** [FHell/NetworkDynamics.jl#20]
@FHell: 

When executed directly diffusion_test.jl throws an error in line 146 at the statement `sef = StaticEdgeFunction(diff_network_st.f)`. This is not part of any `@test` so it didn't turn up earlier. 

```julia
MethodError: no method matching StaticEdgeFunction(::nd_ODE_Static{SimpleGraph{Int64},Array{Float64,1},Array{Float64,1},Array{ODEVertex{typeof(diffusion_vertex!)},1},Array{StaticEdge{typeof(diffusion_edge!)},1}})
Closest candidates are:
  StaticEdgeFunction(::Any, !Matched::Any, !Matched::Any) at /home/micha/git/NetworkDynamics.jl/src/NetworkDynamics.jl:165
top-level scope at diffusion_test.jl:146
```

It's easy to fix this by inserting the correct arguments:

```julia
sef = StaticEdgeFunction(vertex_list,edge_list,g)
```

However, I don't understand what these lines are supposed to do since they are not part of any `@test` . The final print statement gives

```julia
Maximum difference of the static and dynamic edge variables at t=1.0: 0.15737304472602853
```
Is this supposed to be 0? If not what else? Why do we check this?

**Comment by FHell** [comment]
Multithreading resolves this. I'll make a new issue to test StaticEdgeFunction properly.
