### ISSUE TITLE
bounds checking issue in maybe_idx

### ISSUE THREAD

**Issue by lindnemi** [FHell/NetworkDynamics.jl#23]
`maybe_idx` and its 'cousins' disable bounds checking. Yet it's not unlikely that a user passes a parameter array of incorrect dimensions. in this case these functions asses uninitialized memory. we should add a check somewhere

**Comment by lindnemi** [comment]
at least document the current state and its caveats.

**Comment by hexaeder** [comment]
What is the problem here?
```julia
@inline Base.@propagate_inbounds function maybe_idx(p::T, i) where T <: AbstractArray
    p[i]
end
```
disables bound checking only if called inside `@inbounds` context.

Or do you mean the dimensions of the provided parameters should be checked during construction of whole ODE problem in order to disable bounds checking in the core loop?

**Comment by lindnemi** [comment]
By default bounds checking is disabled for the whole core loop. It's somewhat hidden in the `@nd_threads` macro. This may lead to issues if parameters (or in some case initial conditions) are of the wrong dimension. So i was thinking we should check somewhere that all arrays actually have the dimensions that we implicitly assume
