### ISSUE TITLE
No multi-threading in combination with pmap?

### ISSUE THREAD

**Issue by strangeli** [FHell/NetworkDynamics.jl#44]
Hi, 
I got this warning in Julia 1.4.2 when I use parallel = true in NetworkDynamics (network_dynamics and StaticEdgeFunction) while solving an EnsembleProblem with [EnsembleDistributed()](https://docs.sciml.ai/stable/features/ensemble/#EnsembleAlgorithms-1) which is based on pmap. 

```
Warning: You are using multi-threading with only one thread available to
Julia. Consider re-starting Julia with the environment variable
JULIA_NUM_THREADS set to the number of physical cores of your
CPU.
```
The ensemble problem uses pmap and opens as many processors as there is julia processes. I am not sure if the ensemble problem is hindering NetworkDynamics to open multiple threads within the processes or if the IT Service really would need to change JULIA_NUM_THREADS. 

It is not relevant for me at this point, I just want to report it. Simulation time was half without the warnings (parallel = false in NetworkDynamics) though.

**Comment by lindnemi** [comment]
It seems that EnsembleDistributed() is spawning separate julia processes that run on exactly 1 core, thats why network_dynamics complains. Internally ND.jl just parallelizes the core loop with the Threads.@threads macro. This has some overhead which leads to the slowdown, when just one core is available to the julia process.

At the moment you have to decide if you want  either the EnsembleProblem or NetworkDynamics to do the parallelism.

**Comment by lindnemi** [comment]
Closing since there is nothing to change for us here.
