### ISSUE TITLE
Prune exports

### ISSUE THREAD

**Issue by hexaeder** [FHell/NetworkDynamics.jl#53]
I think the exports in some of the modules can be pruned. This would help readers to understand which methods are meant for external use. And its always good idea to keep namespaces clean.

For example `NetworkStructures.jl` exports the `create_idxs`, `create_offsets`,... methods which are solely meant for internal use.

**Comment by lindnemi** [comment]
Good idea. Did you find more of these superfluous exports? 

In any case you could open a pull request and I would be happy to merge these simplifications if all tests pass.

**Comment by hexaeder** [comment]
I haven't found anything else this obvious, my first post seems to be an exaggeration in this regard, sorry.
However since I've collected them: here is a list of everything which is exported by `NetworkDynamics.jl`. Some of them might be unnecessary but hard to avoid using reexport.

   - `NetworkDynamics.jl`
     - `network_dynamics`
   - `Utilities.jl`
     - `maybe_idx`, `p_v_idx`, `p_e_idx`
     - `nd_threads`
     - `oriented_symmetric_edge_sum!`
     - `find_fixpoint`
     - `RootRhs`
     - `find_valid_ic`
     - `syms_containing`, `idx_containing`
   - `ComponentFunctions.jl`
     - `VertexFunction`, `EdgeFunction`
     - `StaticVertex`, `StaticEdge`
     - `ODEVertex`, `ODEEdge`, `DDEVertex`, `StaticDelayEdge`
   - `NetworkStructures.jl`
     - `create_idxs`
     - `create_offsets`
     - `GraphStruct, GraphData`
     - `EdgeData, VertexData`
     - `construct_mass_matrix`
     - `view_v, view_e`
     - `GetGD, GetGS`
     - `ND_Solution`
   - `nd_ODE_ODE.jl`
     - `nd_ODE_ODE`
   - `nd_ODE_Static.jl`
     - `nd_ODE_Static`
     - `StaticEdgeFunction`
   - `nd_DDE_Static.jl`
     - `nd_DDE_Static`
