### ISSUE TITLE
Bug: wrong eltype for EdgeData/VertexData

### ISSUE THREAD

**Issue by hexaeder** [FHell/NetworkDynamics.jl#54]
The bug is already commented in the code but i could not find a corresponding issue.

```julia
struct EdgeData{G,T} <: AbstractArray{T, 1} # This is a lie. The elements of EdgeData are not of type T but of type eltype(T).
```
This is potentially a big problem if users might use advanced linear algebra in the edges/vertices. This issue is closely related to #32.

I've tried to possible ways to fix this:
- change the meaning of `Tv` and `Te` to be the eltype. But than one loses some flexibility in the data type,  which is bad.
```julia
struct GraphDataBuffer{Tv, Te}
    v_array::Vector{Te}
    e_array::Vector{Tv}
end
``` 
- The better solution is to add a new type parameter for the eltype. Unfortunately, these parameters `eltype_Tv` and `eltype_Te` bubble all the way up to the signature of `GraphData` in order to make it typestable.

```julia
abstract type GraphDataView{T} <: AbstractVector{T} end

struct VertexView{Tv, Te, T} <: GraphDataView{T}
    parent::GraphDataBuffer{Tv, Te}
    idx_offset::Int
    len::Int
end

function VertexView(data::GraphDataBuffer{Tv, Te}, range::UnitRange) where {Tv, Te}
    offset = first(range) - 1
    len = length(range)
    VertexView{Tv, Te, eltype(Tv)}(data, offset, len)
end
```

**Comment by lindnemi** [comment]
I think the GraphDataBuffer design proposed by Frank earlier this year is already an improvement over the current EdgeData design and I'm not entirely sure why we didn't merge. The changes you suggest seem to make it even more general, which is great. Could you give a brief example in which case you would need that extra flexibility in the data type?

On the other hand we've been thinking of a more general redesign of the whole GraphData / Edge Data approach. Since Julia 1.5. views are no longer allocating, so instead of designing our own views, we might just use Julias standard views... I would like to see a benchmark of that but haven't had the time to make one.

**Comment by lindnemi** [comment]
For example the central edge loop might look like this:
```julia
    @nd_threads d.parallel for i in 1:gs.num_e
        maybe_idx(d.edges!, i).f!(view(gd.e_array, i:i)), view(dx, gs.s_e_idx[i]), view(dx, gs.d_e_idx[i]), p_e_idx(p, i), t)
    end
```
A first benchmark indicates that it does what it should in the same amount of time but we will need more careful testing.

It semms for Julia >= 1.5 we might drop the GraphData struct almost entirely, just keeping an array of internal edge variables and the various sets of precomputed indices.

**Comment by hexaeder** [comment]
Ah okay I found my misunderstanding.
```julia
struct EdgeData{GDB, elE} <: AbstractArray{elE, 1}
    gdb::GDB
    idx_offset::Int
    len::Int
end
```
I haven't look thoroughly through the commit for the `GraphDataBuffer`. Since `GDB` is introduced as an Type Parameter (which is basically is a shorthand for `Tv` and `Te`) the problem is already fully solved in the commit.

Regarding the non-allocating views in 1.5: I played alot with the internes in order to understand how in fully works. I've created a version which has (alongside many other small changes) pure view creation instead of these 'mutable' views. You can find it here: https://github.com/hexaeder/NetworkDynamics.jl/tree/nonalloc_views

I was able to get the calls nonallocating but it was slower: 2.2 micro seconds for the benchmark call with 100 nodes instead of 1.3 micro seconds on my machine.

**Comment by lindnemi** [comment]
What do you mean with pure views vs. mutable views?
My benchmarks don't show any problems with the Julia native views. In fact they seem to be faster. On 100 nodes, 900 edges I get: 7.3 sec( master) / 5.8 sec (using some julia views)

All i did is to partially rewrite the central loop:

```julia
function (d::nd_ODE_Static)(dx, x, p, t)
    gd = prep_gd(dx, x, d.graph_data, d.graph_structure)
    gs = d.graph_structure

    @nd_threads d.parallel for i in 1:gs.num_e
        maybe_idx(d.edges!, i).f!(view(gd.e_array, i:i), view(x, gs.s_e_idx[i]), view(x, gs.d_e_idx[i]), p_e_idx(p, i), t)
    end

    @nd_threads d.parallel for i in 1:gs.num_v
        maybe_idx(d.vertices!,i).f!(view(dx,d.graph_structure.v_idx[i]), view(gd.v_array, i:i), gd.e_s_v[i], gd.e_d_v[i], p_v_idx(p, i), t)
    end

    nothing
end
```
[e_s_v and e_d_v could be replaced with views as well]

**Comment by hexaeder** [comment]
I was refering to the `EdgeData`, `VertexData` construct by mutable views, because they are basically a view type where the underlying data might change (of curse they are not really mutable instad pointing to something mutable as a parent). With pure views I've refered to creating new `SubArray` types every call.

I found the `e_s_v` and `e_d_v` to be the problem since they need to be cached in an array. But my "benchmarks" are far less meaningfull than yours because I was playing around with a lot of the internals in order to get an understanding for how the package actually work.

**Comment by hexaeder** [comment]
fyi, for the nonallocating caching of the `e_s_v` and `e_d_v` i've added a new fileds to the `GraphData`
```julia
    _out_edge_view_cache::Vector{Vector{viewtype}}
    _in_edge_view_cache::Vector{Vector{viewtype}}
```
where the type of the view has to be concrete in order to be performent, somthing like
```const viewtype = SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}```
(which should incorporate the type parameters eventually).

For every call one have to do something like
```julia
@inline function out_edges_views(gd::GraphDataMapping, vert_index)
    # get view cach for the vert
    @inbounds cache = gd._out_edge_view_cache[vert_index]
    # loop over all out edges
    for i in 1:length(cache)
        @inbounds cache[i] = view(gd.v_array, [retrive index range])
    end
    cache
end
```

**Comment by lindnemi** [comment]
Hmmm, but we have an internal edge state array called `e_array`. Can't we just get the right set of indices and create a view into `e_array` right in nd_ODE_static. I want to look into that  in more detail tomorrow.

**Comment by hexaeder** [comment]
For the outgoing as well as the incoming edges the vertex function expects an AbstractArray of views/EdgeData to data. This can't be represented as a matrix (i.e. a 2 dimensional view) since all of the edges might have different number of dimensions. Therfore one has to use some kind of Array-of-Views structure. In order to avoid allocations for the function calls the outer array has to be cached in some way.

It might be possible to stack all the views together as an StaticArray which shouldn't require heap allocation, but i'm not sure whether this is even possible to create a StaticArray for such complex datatype.

**Comment by lindnemi** [comment]
You are right. The most difficult part is e_s_v, e_d_v. I thought that views of views might be the solution, but i didn't manage to get rid of that last allocation per edge. My efforts are in this branch: https://github.com/FHell/NetworkDynamics.jl/tree/edgeviews

The GraphData object can be boiled down a lot and GraphStructure could be simplified as well. That said, I couldn't reproduce yesterdays benchmark that showed an advantage of Julia native views over our EdgeData objects. Switiching to views seems to be more of a cosmetic improvement for the code structure.

We still plan to get rid of e_s_v, e_d_v entirely by doing the aggregation of individual edges contributions not within each vertex but already before that in an aggregator function (e.g. like this https://github.com/FHell/NetworkDynamics.jl/blob/ml_agg/src/nd_ODE_Static.jl)

Also I wrote a new benchmarking script based on 2nd order Kuramoto oscillators, that verifies that the results are correct in addition to timing it. I found it useful for all that index magic, since its easy to confuse things and break the accuracy: https://github.com/FHell/NetworkDynamics.jl/blob/master/benchmarking/time_and_test.jl

**Comment by hexaeder** [comment]
But the aggregation just pushes the problem in another function? At some point it is still necessary to collect all of the outgoing or incoming edges.

In order to have less breaking changes outside of `NetworkStructures.jl` i'd propose a function interface to get the underlying data of the graph which does not depend on on the concrete implementation of `GraphData`. If the functions are inlined this shouldn't affect performance. This would be also very helpful for #49.
```julia
# get the 'view' for the i-th vertex
function get_vertex(gd::GraphData, v_idx) :: AbstractVector{elE}

# get the 'view' for the i-th edge
function get_edge(gd::GraphData, e_idx) :: AbstractVector{elE}

# get the 'view' to the src vertex of the i-th edge
function get_src_vertex(gd::GraphData, e_idx) :: AbstractVector{elV}

# get the 'view' to the dst vertex of the i-th edge
function get_dst_vertex(gd::GraphData, e_idx) :: AbstractVector{elV}

# get all the 'views' to the outgoing edges of the i-th vertex
function get_out_edges(gd::GraphData, v_idx) :: AbstractVector{AbstractVector{elE}}

# get all the 'views' to the incomming edges of the i-th vertex
function get_in_edges(gd::GraphData, v_idx) :: AbstractVector{AbstractVector{elE}}
```
