### ISSUE TITLE
Host documentation online

### ISSUE THREAD

**Issue by Datseris** [FHell/NetworkDynamics.jl#7]
Hi there. Documenter.jl is the go-to standard in creating a documentation for Julia packages. Besides the plethora of features it involves, it also allows you to build your documentation using Julia code.

Documenter.jl also has clear instructions on how you can host your documentation on the very github repository that you host your code, see for example here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

There seems to be a dedicated folder already containing some documentation `docs/` but it is inaccessible.

**Comment by FHell** [comment]
The documentation is already at
https://fhell.github.io/NetworkDynamics.jl/

But there was no link. We need to update the readme to show this, and rework the Docs to start with.

**Comment by Datseris** [comment]
I'd also recommend to replace all Julia code blocks in teh documentation with  `@example` code blocks, to ensure that the output of what you present is indeed what you would like it to be.

**Comment by lindnemi** [comment]
The documentation has been up for a while, so i think this issue can be closed. However one problem with the @example blocks remains. Apparently the ubuntu-worker that builds the docs is missing a library and prints the follwing error message into the documentation:

```
/home/runner/.julia/packages/GR/NSt7D/src/../deps/gr/bin/gksqt: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
connect: Connection refused
GKS: can't connect to GKS socket application
Did you start 'gksqt'?

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```

@Datseris, do you know how to fix this by any chance? It seems in the docs for DynamicalBillards.jl you don't have that problem.

**Comment by Datseris** [comment]
I use PyPlot for DynamicalBilliards.jl . You should report this issue to GR's github page. However, I think that adding:
```
ENV["GKSwstype"] = "100"
```
as the first line of your make.jl tends to fix problems on Travis.

**Comment by Datseris** [comment]
@lindnemi the docs have been up for a while, but at which link? This https://fhell.github.io/NetworkDynamics.jl/ doesn't work for me.

**Comment by lindnemi** [comment]
Thank, I'll try out your suggestions.

docs can be found here: [https://fhell.github.io/NetworkDynamics.jl/dev/]( https://fhell.github.io/NetworkDynamics.jl/dev/)

**Comment by lindnemi** [comment]
I added a redirect from  https://fhell.github.io/NetworkDynamics.jl/  to the dev version of the docs. Eventually the redirect should be changed to the stable version, however, as of now that is terribly out of date. @FHell we should think of incrementing the version to 0.2.1 in order to include the improved docs in the package.
