### ISSUE TITLE
Direction of edges inverted when going from `SimpleWeightedDiGraph` to `SimpleDiGraph`

### ISSUE THREAD

**Issue by Antomek** [FHell/NetworkDynamics.jl#70]
Hello all,

I hope this is the right place to ask this question!
After the recent update of NetworkDynamics.jl the functions no longer work with `SimpleWeightedDiGraph` objects, instead taking a `SimpleDiGraph` object.
In e.g. [the FitzHugh-Nagumo](https://fhell.github.io/NetworkDynamics.jl/stable/directed_and_weighted_graphs/#The-FitzHugh-Nagumo-model) tutorial in the docs this is described.
A slightly modified version of setting up that tutorial:

```julia
using SimpleWeightedGraphs, LightGraphs

# Create lists of sources and destination vertices
sources = [i for i in 1:3]
destinations = [4 for _ in 1:length(sources)]
weights = [1. for _ in 1:length(sources)]

# Construct the weighted and directed graph
g_weighted = SimpleWeightedDiGraph(sources, destinations, weights)
edge_weights = getfield.(collect(edges(g_weighted)), :weight)

# Convert the weighted graph to a simple directed graph
g_directed = SimpleDiGraph(g_weighted)
```

However, this procedure inverts the direction of the edges:
```julia
julia> collect(edges(g_weighted))
3-element Array{SimpleWeightedEdge{Int64,Float64},1}:
 Edge 1 => 4 with weight 1.0
 Edge 2 => 4 with weight 1.0
 Edge 3 => 4 with weight 1.0
```
and
```julia
julia> collect(edges(g_directed))
3-element Array{LightGraphs.SimpleGraphs.SimpleEdge{Int64},1}:
 Edge 4 => 1
 Edge 4 => 2
 Edge 4 => 3
```

Of course this is easily fixed by doing `reverse(g_directed)`, but it is confusing nevertheless.
This might be a SimpleWeightedGraphs.jl issue, [so I posted it there](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/issues/67) as well, but I thought you maybe wanted to be aware of this.

**Comment by lindnemi** [comment]
Hi Thomas, thanks for reporting this issue. Indeed this should be fixed upstream. I'll leave this issue open until it has been fixed by SimpleWeightedGraphs.

**Comment by lindnemi** [comment]
Fixed upstream.
